-- The "default theme" will be the base parent theme for the B2B theme
INSERT INTO BLC_THEME_DEFINITION (THEME_DEFINITION_ID, THEME_NAME, THEME_DESCRIPTION, THEME_PATH, IS_DEFAULT) VALUES (-2, 'B2B Theme', 'B2B theme (inherits from the default theme)', 'b2b-theme', false);

INSERT INTO BLC_THEME_CONFIGURATION (THEME_CONFIGURATION_ID, PARENT_THEME_ID, THEME_DEFINITION_ID, THEME_NAME, DATE_CREATED, DATE_UPDATED, IS_DEFAULT) VALUES (-2, -1, -2, 'B2B Theme Configuration', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false);

-- Make B2B Theme the default
UPDATE BLC_THEME_DEFINITION SET IS_DEFAULT = false where THEME_DEFINITION_ID = -1;
UPDATE BLC_THEME_CONFIGURATION SET IS_DEFAULT = false where THEME_CONFIGURATION_ID = -1;
UPDATE BLC_THEME_DEFINITION SET IS_DEFAULT = true where THEME_DEFINITION_ID = -2;
UPDATE BLC_THEME_CONFIGURATION SET IS_DEFAULT = true where THEME_CONFIGURATION_ID = -2;
